# =====================================================================
# CyberArk vaulting of each RDS instance's MASTER credential
#
# Mirrors the pattern in 04_ec2_compute/vault.tf: create a safe per database
# via the shared idira/safe module, then store the RDS-generated master
# password as a pcloud account. The passwords are generated by the rds/*
# modules (random_password) and surfaced via their outputs; here they are
# written into the vault.
#
# The platform IDs below must ALREADY EXIST in the tenant and be appropriate
# database platforms (set them in terraform.tfvars).
# =====================================================================

module "postgresql_safe" {
  source         = "../modules/idira/safe"
  safe_name      = var.postgresql_safe_name
  description    = "PostgreSQL RDS master credential"
  retention_days = var.db_safe_retention_days
  members        = var.postgresql_safe_members
}

module "mssql_safe" {
  source         = "../modules/idira/safe"
  safe_name      = var.mssql_safe_name
  description    = "MSSQL RDS master credential"
  retention_days = var.db_safe_retention_days
  members        = var.mssql_safe_members
}

# ---------------------------------------------------------------------
# PostgreSQL master account
# ---------------------------------------------------------------------
resource "idsec_pcloud_account" "postgresql_master" {
  platform_id = var.postgresql_platform_id
  username    = module.postgresql.postgresql_username
  address     = module.postgresql.postgresql_address
  secret      = module.postgresql.postgresql_generated_password
  safe_name   = module.postgresql_safe.safe_name
  name        = "${var.team_name}-postgresql-master"

  lifecycle {
    ignore_changes = [
      secret,                      # CPM rotates the password after initial creation
      name,                        # Idira manages naming
      address,                     # cannot be modified on existing accounts
      secret_type,                 # Computed by Idira
      platform_account_properties, # Platform-specific settings
    ]
  }
}

# ---------------------------------------------------------------------
# MSSQL master account
# ---------------------------------------------------------------------
resource "idsec_pcloud_account" "mssql_master" {
  platform_id = var.mssql_platform_id
  username    = module.mssql.mssql_username
  address     = module.mssql.mssql_address
  secret      = module.mssql.mssql_generated_password
  safe_name   = module.mssql_safe.safe_name
  name        = "${var.team_name}-mssql-master"

  lifecycle {
    ignore_changes = [
      secret,
      name,
      address,
      secret_type,
      platform_account_properties,
    ]
  }
}
